######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 13 10:45:18 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qttest.cpp
